#!/bin/bash

echo "======== Installing provisioning scripts to $(pwd) ========"

git clone https://github.com/immutables/provisioning.git
cp -rf ./provisioning/bin/* ./
rm -rf ./provisioning

. ./-im-vars

./im-reset

echo "======== Installed configuration: $GIT_CONFIGURATION_BRANCH ========"
echo "Run ./im-restart to update and launch"
